version: '3.8'
services:
  drupal:
    image: drupal:9
    ports:
      - 8080:80
    volumes:
      - ./drupal-modules:/var/www/html/modules
      - ./drupal-profiles:/var/www/html/profiles
      - ./drupal-themes:/var/www/html/themes
      - ./drupal-sites:/var/www/html/sites
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql
